# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # The available themes options are "default", "air", "sunrise", "mint", "dirt" and "contrast"
title                    : "Oscar Carballal"
title_separator          : "-"
name                     : &name "Oscar Carballal"
description              : &description "PhD student in Mathematics"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : "https://oscarballalso.xyz" # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "academicpages/academicpages.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "perfil.jpg"
  name             : "Oscar Carballal"
  pronouns         : # example: "she/her"  
  bio              : "PhD Student in Mathematics at Universidad Complutense de Madrid"
  location         : "Madrid"
  employer         : "UCM"
  uri              : # URL
  email            : "oscarbal@ucm.es" 

  # Academic websites
  arxiv            : "http://arxiv.org/a/carballal_o_1"
  googlescholar    : "https://scholar.google.es/citations?user=5zzeOzQAAAAJ&hl=es&authuser=2"
  orcid            : "https://orcid.org/0009-0001-6659-744X"
  researchgate     : "https://www.researchgate.net/profile/Oscar-Carballal?ev=hdr_xprf"
  scopus           : # URL
  zotero           : # URL


# Layout Settings
favicon: /images/favicon.ico
include: [".htaccess"]
exclude: ["lib", "config.sh", "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
